### ISSUE TITLE
Hanging on Kernel boot

### ISSUE THREAD

**Issue by Neywiny** [polarfire-soc/polarfire-soc-buildroot-sdk#7]
Hello,

I've been having some issues getting the Kernel to boot when I change specific settings in the config, like adding in a driver. I've modded u-boot to print out a bit more, and it shows me it's getting to the point where it calls kernel(). But then the printing stops, and I don't get any indication that something's working silently (current consumption changes, Ethernet lights, etc). Presumably there's a way to debug this over JTAG, right? I tried going through all the steps with SoftConsole's debugger, but all it shows is that the E51 is doing HSS things and U54_1-3 are suspended in a container and U54_4 is suspended with a SIGINT. The PC values don't line up with the locations u-boot said it put the data into, so I'm thinking virtual memory was started up.

How can I debug this? Not even sure if adding print statements would work at this point, since I don't see the linux_banner get printed out.

Thank you

**Comment by ConchuOD** [comment]
Which kconfig entries have you been changing? If you could attach a diff of your kernel's defconfig compared to the default, that'd be great.

Similarly a log (or screenshot) of the point at which it stops printing (although I assume what you see is U-Boot going "starting kernel" and nothing more).

I'll try to get back to you on debugger configuration tomorrow.

**Comment by Neywiny** [comment]
So the change that breaks it is enabling a DMA driver for a 3rd-party DMA engine sitting in the PL. So it's not an easy thing to reproduce on your side. As mentioned I modded u-boot for more info, but it didn't really help. What it tells me is

> Starting kernel ...
> 
> Quiescing devices
> Removing flags
> Cleaning up
> Calling SMP function
> SMP function returned 0
> Calling kernel function
> 
And then nothing. The DMA driver is enabled with 
DMA_ENGINE=y
DMADEVICES=y
and then their driver =y.
I've tried with the SF_PDMA=y, and UIO_MICROCHIP_PDMA=y, that boots ok. 

There are no error or warnings at compile time, the driver's .o file seems to pop out the other side ok.

Thank you

**Comment by ConchuOD** [comment]
DMADEVICES should be enabled anyway in the defconfig, enabling SF_PDMA also enables DMA_ENGINE. So that would appear to leave you with just their driver.  
Is it possible to build that dma driver as a module, since then you could load it once the serial console is already up? Might save you time and effort if you can, since you could copy the module to the board via scp & you would only need to rebuild the module as you make changes rather than the whole kernel.

To debug from SoftConsole's gdb, you should be able to add vmlinux as a symbol file - but that's mainly useful before virtual memory is configured. earlyprintk should be enabled by default, but won't be output until there's a serial console available.

To use the sbi console, add `earlycon=sbi` to the bootargs/CONFIG_CMDLINE. sbi_console normally outputs on the UART associated with that hart. For example, E51 => MMUART0, U54_1 => MMUART1, etc. You can change this but it needs a custom HSS, with a trivial modification to services/opensbi/platform.c : mpfs_console_getc()

Finally there's the options of looking at the symbol map manually or writing directly to the output shift register of the uart.

**Comment by Neywiny** [comment]
I'll give the sbi a shot. I'm thinking you meant mpfs_console_putc(), but yes I see where it passes the hartid and I can just override that to always be hart 0. It looks like I can't get data through FIC0 out to my RTL correctly. So I'm thinking that your advice has been very helpful for the Linux side, but I'm now realizing I'm not there yet. I enabled another PL driver and my code hangs at the first AXI read. So something is stalled.

I think this DMA driver is probing before the console is available, and so it would also be stalling and causing the system to not boot. So for now I'll start bare metal, making sure the PL is doing what I want, then I will for sure be utilizing your guidance on getting the Linux side up and running.

**Comment by Neywiny** [comment]
Guess I'll close this because it's a PL issue for now. Would still like a good way to debug with vmem, but one step at a time.
